#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# INSTANCE LANGUAGE GETTER/SETTER
#=================================================

get__instance_languages() {
	yq -Mrc '."instance-languages" | join(",")' $install_dir/config.yaml
}

set__instance_languages() {
	# We cannot use ynh_write_var_in_file as it ends up over-escaping characters
	# We cannot use yq as its version in YunoHost, as of 2025-08-13,
	# does not ship with the 'style' option that would prevent us from defacing the config.yaml file
	instance_languages="[\"${instance_languages//,/\"\, \"}\"]"
	ynh_replace_regex --match="^instance-languages:.*" --replace="instance-languages: $instance_languages" --file=$install_dir/config.yaml
}

#=================================================

ynh_app_config_run "$1"

