#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

# import needed settings
port_dns_over_tls=$(ynh_app_setting_get --key=port_dns_over_tls)
port_dns_over_quic=$(ynh_app_setting_get --key=port_dns_over_quic)

#=================================================
# SPECIFIC SETTERS
#=================================================

set__instance_languages() {
    # custom setter because we need to add the square brackets
    ynh_app_setting_set --key=instance_languages --value="$instance_languages"
    ynh_write_var_in_file --file="$install_dir/settings.yml" --key="instance-languages" --value="[$instance_languages]"
}

#=================================================

ynh_app_config_run "$1"

