#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

#REMOVEME? ynh_clean_setup () {
	### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
#REMOVEME? ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

#REMOVEME? app="$YNH_APP_INSTANCE_NAME"

landing_page_user=""

#REMOVEME? domain="$YNH_APP_ARG_DOMAIN"
path="/"

client_max_body_size="100M"

#REMOVEME? admin="$YNH_APP_ARG_ADMIN"
#REMOVEME? email="$YNH_APP_ARG_EMAIL"
#REMOVEME? password="$YNH_APP_ARG_PASSWORD"

# Config stuff:

#REMOVEME? accounts_registration_open=$(convert_bool "$YNH_APP_ARG_ACCOUNTS_REGISTRATION_OPEN")
#REMOVEME? accounts_approval_required=$(convert_bool "$YNH_APP_ARG_ACCOUNTS_APPROVAL_REQUIRED")
#REMOVEME? accounts_reason_required=$(convert_bool "$YNH_APP_ARG_ACCOUNTS_REASON_REQUIRED")
accounts_allow_custom_css="false"

instance_expose_peers="false"
instance_expose_suspended="false"
instance_expose_suspended_web="false"
instance_expose_public_timeline="false"
instance_deliver_to_shared_inboxes="true"

media_image_max_size="10485760"
media_video_max_size="41943040"
media_description_min_chars="0"
media_description_max_chars="500"
media_remote_cache_days="30"
media_emoji_local_max_size="51200"
media_emoji_remote_max_size="102400"

storage_backend="local"
storage_s3_endpoint=""
storage_s3_proxy="false"
storage_s3_access_key=""
storage_s3_secret_key=""
storage_s3_bucket=""

statuses_max_chars="5000"
statuses_cw_max_chars="100"
statuses_poll_max_options="6"
statuses_poll_option_max_chars="50"
statuses_media_max_files="6"

smtp_host="localhost"
smtp_port="25"
smtp_username=""
smtp_password=""
smtp_from="noreply@$domain"
smtp_disclose_recipients="false"

advanced_cookies_samesite="lax"
advanced_rate_limit_requests="300"

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

#REMOVEME? ynh_script_progression --message="Validating installation parameters..." --weight=1

#REMOVEME? install_dir="/var/www/$app"
#REMOVEME? test ! -e "$install_dir" || ynh_die --message="This path already contains a folder"

#REMOVEME? ynh_webpath_register --app="$app" --domain="$domain" --path="$path"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
#REMOVEME? ynh_script_progression --message="Storing installation settings..." --weight=1

#REMOVEME? ynh_app_setting_set --app="$app" --key=install_dir --value="$install_dir"

ynh_app_setting_set --app="$app" --key=landing_page_user --value="$landing_page_user"

#REMOVEME? ynh_app_setting_set --app="$app" --key=domain --value="$domain"
#REMOVEME? ynh_app_setting_set --app="$app" --key=path --value="$path"

ynh_app_setting_set --app="$app" --key=client_max_body_size --value="$client_max_body_size"

#REMOVEME? ynh_app_setting_set --app="$app" --key=admin --value="$admin"
ynh_app_setting_set --app="$app" --key=email --value="$email"
#REMOVEME? ynh_app_setting_set --app="$app" --key=password --value="$password"

ynh_app_setting_set --app="$app" --key=accounts_registration_open --value="$accounts_registration_open"
ynh_app_setting_set --app="$app" --key=accounts_approval_required --value="$accounts_approval_required"
ynh_app_setting_set --app="$app" --key=accounts_reason_required --value="$accounts_reason_required"
ynh_app_setting_set --app="$app" --key=accounts_allow_custom_css --value="$accounts_allow_custom_css"

ynh_app_setting_set --app="$app" --key=instance_expose_peers --value="$instance_expose_peers"
ynh_app_setting_set --app="$app" --key=instance_expose_suspended --value="$instance_expose_suspended"
ynh_app_setting_set --app="$app" --key=instance_expose_suspended_web --value="$instance_expose_suspended_web"
ynh_app_setting_set --app="$app" --key=instance_expose_public_timeline --value="$instance_expose_public_timeline"
ynh_app_setting_set --app="$app" --key=instance_deliver_to_shared_inboxes --value="$instance_deliver_to_shared_inboxes"

ynh_app_setting_set --app="$app" --key=media_image_max_size --value="$media_image_max_size"
ynh_app_setting_set --app="$app" --key=media_video_max_size --value="$media_video_max_size"
ynh_app_setting_set --app="$app" --key=media_description_min_chars --value="$media_description_min_chars"
ynh_app_setting_set --app="$app" --key=media_description_max_chars --value="$media_description_max_chars"
ynh_app_setting_set --app="$app" --key=media_remote_cache_days --value="$media_remote_cache_days"
ynh_app_setting_set --app="$app" --key=media_emoji_local_max_size --value="$media_emoji_local_max_size"
ynh_app_setting_set --app="$app" --key=media_emoji_remote_max_size --value="$media_emoji_remote_max_size"

ynh_app_setting_set --app="$app" --key=storage_backend --value="$storage_backend"
ynh_app_setting_set --app="$app" --key=storage_s3_endpoint --value="$storage_s3_endpoint"
ynh_app_setting_set --app="$app" --key=storage_s3_proxy --value="$storage_s3_proxy"
ynh_app_setting_set --app="$app" --key=storage_s3_access_key --value="$storage_s3_access_key"
ynh_app_setting_set --app="$app" --key=storage_s3_secret_key --value="$storage_s3_secret_key"
ynh_app_setting_set --app="$app" --key=storage_s3_bucket --value="$storage_s3_bucket"

ynh_app_setting_set --app="$app" --key=statuses_max_chars --value="$statuses_max_chars"
ynh_app_setting_set --app="$app" --key=statuses_cw_max_chars --value="$statuses_cw_max_chars"
ynh_app_setting_set --app="$app" --key=statuses_poll_max_options --value="$statuses_poll_max_options"
ynh_app_setting_set --app="$app" --key=statuses_poll_option_max_chars --value="$statuses_poll_option_max_chars"
ynh_app_setting_set --app="$app" --key=statuses_media_max_files --value="$statuses_media_max_files"

ynh_app_setting_set --app="$app" --key=smtp_host --value="$smtp_host"
#REMOVEME? ynh_app_setting_set --app="$app" --key=smtp_port --value="$smtp_port"
ynh_app_setting_set --app="$app" --key=smtp_username --value="$smtp_username"
#REMOVEME? ynh_app_setting_set --app="$app" --key=smtp_password --value="$smtp_password"
ynh_app_setting_set --app="$app" --key=smtp_from --value="$smtp_from"
ynh_app_setting_set --app="$app" --key=smtp_disclose_recipients --value="$smtp_disclose_recipients"

ynh_app_setting_set --app="$app" --key=advanced_cookies_samesite --value="$advanced_cookies_samesite"
ynh_app_setting_set --app="$app" --key=advanced_rate_limit_requests --value="$advanced_rate_limit_requests"

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================
#REMOVEME? ynh_script_progression --message="Finding an available port..." --weight=1

# Find an available port
#REMOVEME? port=$(ynh_find_port --port=8095)
#REMOVEME? ynh_app_setting_set --app="$app" --key=port --value="$port"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
#REMOVEME? ynh_script_progression --message="Installing dependencies..." --weight=5

#REMOVEME? ynh_exec_warn_less ynh_install_app_dependencies "$pkg_dependencies"

#=================================================
# CREATE DEDICATED USER
#=================================================
#REMOVEME? ynh_script_progression --message="Configuring system user..." --weight=1

# Create a system user
#REMOVEME? ynh_system_user_create --username="$app" --home_dir="$install_dir"

#=================================================
# CREATE A POSTGRESQL DATABASE
#=================================================
#REMOVEME? ynh_script_progression --message="Creating a PostgreSQL database..." --weight=5

#REMOVEME? db_name=$(ynh_sanitize_dbid --db_name="$app")
#REMOVEME? db_user="$db_name"
#REMOVEME? db_pwd=$(ynh_string_random --length=30)
#REMOVEME? ynh_app_setting_set --app="$app" --key=db_name --value="$db_name"
#REMOVEME? ynh_app_setting_set --app="$app" --key=db_user --value="$db_user"
#REMOVEME? ynh_app_setting_set --app="$app" --key=db_pwd --value="$db_pwd"
#REMOVEME? ynh_psql_test_if_first_run
#REMOVEME? ynh_psql_setup_db --db_user="$db_user" --db_name="$db_name" --db_pwd="$db_pwd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

### `ynh_setup_source` is used to install an app from a zip or tar.gz file,
### downloaded from an upstream source, like a git repository.
### `ynh_setup_source` use the file conf/app.src

# detect_arch comes from _common.sh / personnal helpers
architecture=$(detect_arch)

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" 

# FIXME: this should be managed by the core in the future
# Here, as a packager, you may have to tweak the ownerhsip/permissions
# such that the appropriate users (e.g. maybe www-data) can access
# files in some cases.
# But FOR THE LOVE OF GOD, do not allow r/x for "others" on the entire folder _
# this will be treated as a security issue.
chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

# Create a dedicated NGINX config for the main domain
ynh_add_nginx_config

#=================================================
# CREATE DATA DIRECTORY
#=================================================
ynh_script_progression --message="Creating a data directory..." --weight=1

#REMOVEME? data_dir=/home/yunohost.app/$app
#REMOVEME? ynh_app_setting_set --app="$app" --key=data_dir --value="$data_dir"

mkdir -p "$data_dir"

# FIXME: this should be managed by the core in the future
# Here, as a packager, you may have to tweak the ownerhsip/permissions
# such that the appropriate users (e.g. maybe www-data) can access
# files in some cases.
# But FOR THE LOVE OF GOD, do not allow r/x for "others" on the entire folder -
# this will be treated as a security issue.
chmod 750 "$data_dir"
chmod -R o-rwx "$data_dir"
chown -R "$app:www-data" "$data_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="config.yaml" --destination="$install_dir/config.yaml"

# FIXME: this should be handled by the core in the future
# You may need to use chmod 600 instead of 400,
# for example if the app is expected to be able to modify its own config
chmod 400 "$install_dir/config.yaml"
chown "$app:$app" "$install_dir/config.yaml"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..." --weight=1

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Configuring log rotation..." --weight=1

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1

yunohost service add "$app" --description="Gotosocial server" --log="/var/log/$app/$app.log"

#=================================================
# CREATE ADMIN USER
#=================================================
ynh_script_progression --message="Creating gotosocial admin user..." --weight=1

"$install_dir"/gotosocial --config-path "$install_dir/config.yaml" admin account create --username "$admin" --email "$email" --password "$password"

"$install_dir"/gotosocial --config-path "$install_dir/config.yaml" admin account promote --username "$admin"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# SETUP SSOWAT
#=================================================
#REMOVEME? ynh_script_progression --message="Configuring permissions..." --weight=1

# Everyone can access the app.
#REMOVEME? ynh_permission_update --permission="main" --add="visitors"

#=================================================
# RELOAD NGINX
#=================================================
#REMOVEME? ynh_script_progression --message="Reloading NGINX web server..." --weight=1

#REMOVEME? ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
